raw7_map = {
    0: 'None',
    1: 'No Fire',
    2: 'No Water',
    3: 'Wood/Light/Dark only',
    4: 'No Wood',
    5: 'Water/Light/Dark only',
    6: 'Fire/Light/Dark only',
    8: 'No Light',
    9: 'Water/Wood/Dark only',
    10: 'Fire/Wood/Dark only',
    12: 'Fire/Water/Dark only',
    16: 'No Dark',
    17: 'Water/Wood/Light only',
    18: 'Fire/Wood/Light only',
    20: 'Fire/Water/Light only',
    24: 'Tricolor',
    32: 'No RCV',
    64: 'Skills Invalid',
    128: 'Leader Skill Invalid',
    256: 'No Continues',
    259: 'Wood/Light/Dark only',
    261: 'Water/Light/Dark only',
    274: 'Fire/Wood/Light only',
    276: 'No Wood/Dark',
    280: 'Tricolor',
    288: 'No RCV',
    768: 'No Clue',
    800: 'No RCV',
    1024: 'Awoken Skills Invalid',
    1056: 'No RCV, Awoken Skills Invalid',
    1280: 'Awoken Skills Invalid',
    1312: 'No RCV, Awoken Skills Invalid',
    1792: 'Awoken Skills Invalid',
    2048: 'Assists Invalid'
}
