# Generated by Django 2.1 on 2019-01-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='sellCoin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='sellMP',
            field=models.IntegerField(default=0),
        ),
    ]
