# Generated by Django 2.0.7 on 2019-03-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='server',
            field=models.CharField(default='', max_length=2),
        ),
    ]
