# Generated by Django 2.0.7 on 2018-07-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterdata',
            name='awakenings',
            field=models.TextField(default=''),
        ),
    ]
