# Generated by Django 2.0.7 on 2019-01-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('effect', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
