# Generated by Django 2.0.7 on 2019-01-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0002_enemyskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemyskill',
            name='enemy_skill_id',
            field=models.IntegerField(default=-1),
        ),
    ]
