# Generated by Django 2.0.7 on 2019-01-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0003_auto_20190115_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='dmg_reduction',
            field=models.FloatField(default=0),
        ),
    ]
