# Generated by Django 2.0.7 on 2019-01-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0003_enemyskill_enemy_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='enemy_skills',
            field=models.TextField(default=''),
        ),
    ]
