# Generated by Django 2.0.7 on 2019-01-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0004_monster_enemy_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemyskill',
            name='effect',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enemyskill',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
