# Generated by Django 2.0.7 on 2019-02-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0005_auto_20190131_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='dropDungeons',
            field=models.TextField(default=''),
        ),
    ]
