# Generated by Django 2.0.7 on 2019-02-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0006_monster_dropdungeons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='dropDungeons',
        ),
    ]
