# Generated by Django 2.0.7 on 2019-02-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0007_remove_monster_dropdungeons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemyskill',
            name='effect',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='enemyskill',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
