# Generated by Django 2.0.7 on 2018-08-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuerrillaDungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('startTime', models.CharField(default='', max_length=200)),
                ('endTime', models.CharField(default=0, max_length=200)),
                ('startSecs', models.FloatField(default=0)),
                ('endSecs', models.FloatField(default=0)),
                ('server', models.CharField(default='', max_length=10)),
                ('group', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
