# Generated by Django 2.0.7 on 2019-02-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guerrilladungeon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guerrilladungeon',
            name='image_id',
            field=models.IntegerField(default=1),
        ),
    ]
