# Generated by Django 2.0.7 on 2018-08-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guerrilladungeon', '0002_auto_20180716_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='guerrilladungeon',
            name='endSecs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='guerrilladungeon',
            name='startSecs',
            field=models.FloatField(default=0),
        ),
    ]
