# Generated by Django 2.0.7 on 2018-10-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(default='', max_length=5)),
                ('itemID', models.IntegerField(default=0)),
                ('itemType', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
