# Generated by Django 2.0.7 on 2018-10-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='itemName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='itemType',
            field=models.CharField(choices=[('', 'Select a problem child'), ('askill', 'Active Skill'), ('lskill', 'LeaderSkill'), ('monster', 'Monster')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='server',
            field=models.CharField(choices=[('', 'Select a server'), ('na', 'NA'), ('jp', 'JP')], default='', max_length=5),
        ),
    ]
