# Generated by Django 2.0.7 on 2018-10-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20181016_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolveStatus',
            field=models.BooleanField(default=False),
        ),
    ]
