# Generated by Django 2.0.7 on 2018-07-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('skillID', models.IntegerField(blank=True)),
                ('skillType', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeSkillID', models.IntegerField(blank=True)),
                ('attributeID', models.IntegerField()),
                ('baseID', models.IntegerField()),
                ('cardID', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('leaderSkillID', models.IntegerField(blank=True)),
                ('maxATK', models.IntegerField()),
                ('maxHP', models.IntegerField()),
                ('maxLevel', models.IntegerField()),
                ('maxRCV', models.IntegerField()),
                ('minATK', models.IntegerField()),
                ('minHP', models.IntegerField()),
                ('minRCV', models.IntegerField()),
                ('name', models.CharField(default='', max_length=200)),
                ('rarity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSkill',
            fields=[
                ('leaderskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monsterdatabase.LeaderSkill')),
                ('levels', models.IntegerField(default=0)),
                ('maxTurns', models.IntegerField(blank=True)),
                ('minTurns', models.IntegerField(blank=True)),
            ],
            bases=('monsterdatabase.leaderskill',),
        ),
        migrations.AddField(
            model_name='cardna',
            name='leaderSkill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_skill', to='monsterdatabase.LeaderSkill'),
        ),
        migrations.AddField(
            model_name='cardna',
            name='monster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monster', to='monsterdatabase.MonsterData'),
        ),
        migrations.AddField(
            model_name='cardna',
            name='activeSkill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_skill', to='monsterdatabase.ActiveSkill'),
        ),
    ]
