# Generated by Django 2.0.7 on 2018-07-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardna',
            name='activeSkill',
        ),
        migrations.AddField(
            model_name='cardna',
            name='activeSkill',
            field=models.ManyToManyField(to='monsterdatabase.ActiveSkill'),
        ),
        migrations.RemoveField(
            model_name='cardna',
            name='leaderSkill',
        ),
        migrations.AddField(
            model_name='cardna',
            name='leaderSkill',
            field=models.ManyToManyField(to='monsterdatabase.LeaderSkill'),
        ),
    ]
