# Generated by Django 2.0.7 on 2018-07-12 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardna',
            name='leaderSkill',
        ),
        migrations.RemoveField(
            model_name='cardna',
            name='monster',
        ),
        migrations.AlterField(
            model_name='cardna',
            name='activeSkill',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_skill', to='monsterdatabase.ActiveSkill'),
        ),
    ]
