# Generated by Django 2.0.7 on 2018-07-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterdata',
            name='atk99',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='hp99',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='rcv99',
            field=models.IntegerField(default=0),
        ),
    ]
