# Generated by Django 2.0.7 on 2018-07-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0002_auto_20180713_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterdata',
            name='ancestorID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='attributeID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='baseID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='cardID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='inheritable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='isCollab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='isReleased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='isUlt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='maxATK',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='maxHP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='maxLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='maxRCV',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='maxXP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='minATK',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='minHP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='minRCV',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='rarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monsterdata',
            name='subAttributeID',
            field=models.IntegerField(default=0),
        ),
    ]
