# Generated by Django 2.0.7 on 2018-07-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0002_auto_20180715_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Awakening',
        ),
    ]
