# Generated by Django 2.0.7 on 2018-07-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0002_auto_20180711_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonsterData',
        ),
    ]
