# Generated by Django 2.0.7 on 2018-07-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0003_delete_monsterdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardna',
            name='leaderSkill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_skill', to='monsterdatabase.LeaderSkill'),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='maxTurns',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='minTurns',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cardna',
            name='activeSkill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_skill', to='monsterdatabase.ActiveSkill'),
        ),
        migrations.AlterField(
            model_name='leaderskill',
            name='skillID',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='leaderskill',
            name='skillType',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
