# Generated by Django 2.0.7 on 2018-07-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0003_auto_20180713_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterdata',
            name='nextEvo',
            field=models.IntegerField(default=0),
        ),
    ]
