# Generated by Django 2.0.7 on 2018-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0003_delete_awakening'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterdata',
            name='superAwakenings',
            field=models.TextField(default=''),
        ),
    ]
