# Generated by Django 2.0.7 on 2018-07-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0004_auto_20180712_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeSkillID', models.IntegerField(blank=True)),
                ('attributeID', models.IntegerField()),
                ('baseID', models.IntegerField()),
                ('cardID', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('leaderSkillID', models.IntegerField(blank=True)),
                ('maxATK', models.IntegerField()),
                ('maxHP', models.IntegerField()),
                ('maxLevel', models.IntegerField()),
                ('maxRCV', models.IntegerField()),
                ('minATK', models.IntegerField()),
                ('minHP', models.IntegerField()),
                ('minRCV', models.IntegerField()),
                ('name', models.CharField(default='', max_length=200)),
                ('rarity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cardna',
            name='monster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster', to='monsterdatabase.MonsterData'),
        ),
    ]
