# Generated by Django 2.0.7 on 2018-07-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0004_monsterdata_nextevo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evo', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='monsterdata',
            name='nextEvo',
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='evolutions',
            field=models.ManyToManyField(to='monsterdatabase.Evolution'),
        ),
    ]
