# Generated by Django 2.0.7 on 2018-07-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabase', '0005_auto_20180713_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterdata',
            name='evomat1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='evomat2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='evomat3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='evomat4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='evomat5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='unevomat1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='unevomat2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='unevomat3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='unevomat4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterdata',
            name='unevomat5',
            field=models.IntegerField(default=0),
        ),
    ]
