# Generated by Django 2.0.7 on 2018-07-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonusdungeon', '0002_auto_20180718_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='dungeonType',
            field=models.CharField(default='', max_length=100),
        ),
    ]
