# Generated by Django 2.0.7 on 2018-07-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonusdungeon', '0003_dungeon_dungeontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dungeon',
            name='dungeonType',
        ),
    ]
