# Generated by Django 2.0.7 on 2018-07-17 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0005_auto_20180716_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeontoday',
            name='listingDate',
            field=models.DateField(default=datetime.date(2018, 7, 17)),
        ),
    ]
