# Generated by Django 2.0.7 on 2018-07-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonusdungeon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='bonusEnd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='bonusName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='bonusStart',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='endTime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='startTime',
            field=models.FloatField(default=0),
        ),
    ]
