AWAKENINGS = {
    '': 0,
    'Enhanced HP': 1,
    'Enhanced Attack': 2,
    'Enhanced Heal': 3,
    'Reduce Fire Damage': 4,
    'Reduce Water Damage': 5,
    'Reduce Wood Damage': 6,
    'Reduce Light Damage': 7,
    'Reduce Dark Damage': 8,
    'Auto-Recover': 9,
    'Resistance-Bind': 10,
    'Resistance-Dark': 11,
    'Resistance-Jammers': 12,
    'Resistance-Poison': 13,
    'Enhanced Fire Orbs': 14,
    'Enhanced Water Orbs': 15,
    'Enhanced Wood Orbs': 16,
    'Enhanced Light Orbs': 17,
    'Enhanced Dark Orbs': 18,
    'Extend Time': 19,
    'Recover Bind': 20,
    'Skill Boost': 21,
    'Enhanced Fire Att.': 22,
    'Enhanced Water Att.': 23,
    'Enhanced Wood Att.': 24,
    'Enhanced Light Att.': 25,
    'Enhanced Dark Att.': 26,
    'Two-Pronged Attack': 27,
    'Resistance-Skill Bind': 28,
    'Enhanced Heal Orbs': 29,
    'Multi Boost': 30,
    'Dragon Killer': 31,
    'God Killer': 32,
    'Devil Killer': 33,
    'Machine Killer': 34,
    'Balanced Killer': 35,
    'Attacker Killer': 36,
    'Physical Killer': 37,
    'Healer Killer': 38,
    'Evolve Material Killer': 39,
    'Awaken Material Killer': 40,
    'Enhance Material Killer': 41,
    'Vendor Material Killer': 42,
    'Enhanced Combo': 43,
    'Guard Break': 44,
    'Additional Attack': 45,
    'Enhanced Team HP': 46,
    'Enhanced Team RCV': 47,
    'Damage Void Shield Penetration': 48,
    'Awoken Assist': 49,
    'Super Additional Attack': 50,
    'Skill Charge': 51,
    'Resistance-Bind＋': 52,
    'Resistance-Cloud': 54,
    'Extend Time＋': 53,
    'Resistance-Board Restrict': 55,
    'Skill Boost＋': 56,
    'Enhance when HP is above 80%': 57,
    'Enhance when HP is below 50%': 58,
    'L-Shape Damage Reduction': 59,
    'L-Shape Attack': 60,
    'Super Enhanced Combo': 61,
    'Combo Orb': 62,
    'Skill Voice': 63,
    'Dungeon Bonus': 64,
    'Reduced HP': 65,
    'Reduced Attack': 66,
    'Reduced RCV': 67,
}
