# Generated by Django 2.0.7 on 2019-06-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='type_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='type_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='type_3',
            field=models.IntegerField(default=0),
        ),
    ]
