# Generated by Django 2.0.7 on 2019-06-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='unevo_mat_1',
            new_name='un_evo_mat_1',
        ),
        migrations.RenameField(
            model_name='monster',
            old_name='unevo_mat_2',
            new_name='un_evo_mat_2',
        ),
        migrations.RenameField(
            model_name='monster',
            old_name='unevo_mat_3',
            new_name='un_evo_mat_3',
        ),
        migrations.RenameField(
            model_name='monster',
            old_name='unevo_mat_4',
            new_name='un_evo_mat_4',
        ),
        migrations.RenameField(
            model_name='monster',
            old_name='unevo_mat_5',
            new_name='un_evo_mat_5',
        ),
    ]
