# Generated by Django 2.0.7 on 2019-06-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_auto_20190623_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='un_evolution',
            field=models.TextField(default=''),
        ),
    ]
