# Generated by Django 2.0.7 on 2019-06-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_monster_un_evolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='un_evolution',
        ),
    ]
