# Generated by Django 2.0.7 on 2019-06-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_auto_20190622_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='base_id',
        ),
    ]
