# Generated by Django 2.0.7 on 2019-06-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0004_remove_monster_un_evolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='related_dungeons',
            field=models.TextField(default=''),
        ),
    ]
