# Generated by Django 2.2.3 on 2019-07-23 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0005_monster_related_dungeons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnemySkill',
        ),
        migrations.DeleteModel(
            name='Evolution',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
