# Generated by Django 2.0.7 on 2019-08-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0006_auto_20190722_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='awakenings_raw',
        ),
    ]
