# Generated by Django 2.0.7 on 2019-09-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0008_monster_collab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='type_1',
            new_name='type_1_id',
        ),
        migrations.RenameField(
            model_name='monster',
            old_name='type_2',
            new_name='type_2_id',
        ),
        migrations.RenameField(
            model_name='monster',
            old_name='type_3',
            new_name='type_3_id',
        ),
    ]
