# Generated by Django 2.0.7 on 2019-09-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0010_monster_collab_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='series',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='monster',
            name='series_id',
            field=models.IntegerField(default=0),
        ),
    ]
