# Generated by Django 2.0.7 on 2019-01-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterdatabasejp', '0002_auto_20181205_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='awakenings_raw',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='monster',
            name='evos_raw',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='monster',
            name='sellCoin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='sellMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='superAwakenings_raw',
            field=models.TextField(default=''),
        ),
    ]
