# Generated by Django 2.1 on 2019-01-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('dungeonID', models.IntegerField(default=0)),
                ('dungeonType', models.CharField(default='', max_length=50)),
                ('floorCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorNumber', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('stamina', models.IntegerField(default=0)),
                ('battles', models.IntegerField(default=0)),
                ('possibleDrops', models.TextField(default='')),
                ('dungeonID', models.IntegerField(default=0)),
                ('requiredDungeon', models.IntegerField(default=0)),
                ('modifiers', models.TextField(default='')),
                ('entryRequirement', models.TextField(default='')),
                ('otherModifier', models.TextField(default='')),
            ],
        ),
    ]
