# Generated by Django 2.0.7 on 2018-12-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='possibleDrops',
            field=models.TextField(default=''),
        ),
    ]
