# Generated by Django 2.0.7 on 2019-01-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='battles',
            new_name='waves',
        ),
        migrations.AddField(
            model_name='floor',
            name='enhancedAttribute',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='floor',
            name='enhancedType',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='floor',
            name='fixedTeam',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='floor',
            name='messages',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='floor',
            name='remainingModifiers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='floor',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
