# Generated by Django 2.0.7 on 2019-03-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='server',
            field=models.CharField(default='', max_length=2),
        ),
    ]
