# Generated by Django 2.0.7 on 2019-01-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0002_auto_20190124_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='modifiers',
            new_name='encounterModifiers',
        ),
        migrations.AddField(
            model_name='floor',
            name='teamModifiers',
            field=models.TextField(default=''),
        ),
    ]
