# Generated by Django 2.0.7 on 2019-01-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0003_auto_20190129_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='imageID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floor',
            name='imageID',
            field=models.IntegerField(default=0),
        ),
    ]
