# Generated by Django 2.0.7 on 2018-12-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0004_dungeon_stamina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dungeon',
            name='floorName',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='possibleDrops',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='stamina',
        ),
        migrations.AddField(
            model_name='floor',
            name='dungeonID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floor',
            name='possibleDrops',
            field=models.TextField(default=''),
        ),
    ]
