# Generated by Django 2.0.7 on 2019-01-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0004_auto_20190130_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='requiredFloor',
            field=models.IntegerField(default=0),
        ),
    ]
