# Generated by Django 2.0.7 on 2019-02-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0005_floor_requiredfloor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave', models.IntegerField(default=-1)),
                ('floor', models.IntegerField(default=-1)),
                ('monster_id', models.IntegerField(default=-1)),
                ('hp', models.IntegerField(default=0)),
                ('atk', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('drop_id', models.IntegerField(default=0)),
                ('dungeon_id', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
