# Generated by Django 2.0.7 on 2018-12-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0005_auto_20181211_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='entryRequirement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='floor',
            name='modifiers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='floor',
            name='requiredDungeon',
            field=models.IntegerField(default=0),
        ),
    ]
