# Generated by Django 2.0.7 on 2019-02-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0006_encounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='defense',
            field=models.FloatField(default=0),
        ),
    ]
