# Generated by Django 2.0.7 on 2019-02-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0007_auto_20190202_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
