# Generated by Django 2.0.7 on 2019-02-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0008_encounter_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon_id', models.IntegerField(default=0)),
                ('floor_id', models.IntegerField(default=-1)),
                ('wave_number', models.IntegerField(default=-1)),
                ('encounter_data', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Encounter',
        ),
    ]
