# Generated by Django 2.0.7 on 2019-06-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('dungeon_id', models.IntegerField(default=0)),
                ('dungeon_type', models.CharField(default='', max_length=50)),
                ('floor_count', models.IntegerField(default=0)),
                ('image_id', models.IntegerField(default=0)),
                ('server', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EncounterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon_id', models.IntegerField(default=0)),
                ('floor_id', models.IntegerField(default=-1)),
                ('wave_number', models.IntegerField(default=-1)),
                ('encounter_data', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('stamina', models.IntegerField(default=0)),
                ('waves', models.IntegerField(default=0)),
                ('possible_drops', models.TextField(default='')),
                ('dungeon_id', models.IntegerField(default=0)),
                ('required_dungeon', models.IntegerField(default=0)),
                ('required_floor', models.IntegerField(default=0)),
                ('encounter_modifiers', models.TextField(default='')),
                ('team_modifiers', models.TextField(default='')),
                ('entry_requirement', models.TextField(default='')),
                ('other_modifier', models.TextField(default='')),
                ('messages', models.TextField(default='')),
                ('score', models.IntegerField(default=0)),
                ('fixedTeam', models.TextField(default='')),
                ('remaining_modifiers', models.TextField(default='')),
                ('enhanced_type', models.CharField(default=0, max_length=100)),
                ('enhanced_attribute', models.CharField(default=0, max_length=100)),
                ('image_id', models.IntegerField(default=0)),
            ],
        ),
    ]
