# Generated by Django 2.0.7 on 2019-06-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncounterSet',
        ),
    ]
