# Generated by Django 2.0.7 on 2019-01-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon', models.IntegerField(default=-1)),
                ('monster', models.IntegerField(default=-1)),
                ('skill', models.IntegerField(default=-1)),
            ],
        ),
    ]
