# Generated by Django 2.0.7 on 2018-07-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorNumber', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('stamina', models.IntegerField(default=0)),
                ('battles', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='dungeon',
            name='dungeonType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='floorCount',
            field=models.IntegerField(default=0),
        ),
    ]
