# Generated by Django 2.0.4 on 2018-06-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0002_dungeon_dungeonlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='daily',
            field=models.BooleanField(default=False),
        ),
    ]
