# Generated by Django 2.0.4 on 2018-07-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0003_dungeon_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpnTitle', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
