# Generated by Django 2.0.4 on 2018-07-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0004_dungeontoday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeontoday',
            name='jpnTitle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
