# Generated by Django 2.0.4 on 2018-07-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0005_auto_20180701_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeontoday',
            name='jpnTitle',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
