# Generated by Django 2.0.4 on 2018-07-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0006_auto_20180701_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeontoday',
            name='dungeons',
            field=models.ManyToManyField(to='dungeon.Dungeon'),
        ),
    ]
