# Generated by Django 2.0.4 on 2018-07-03 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0007_dungeontoday_dungeons'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeontoday',
            name='listingDate',
            field=models.CharField(default=datetime.date(2018, 7, 3), max_length=20),
        ),
    ]
