# Generated by Django 2.0.4 on 2018-07-04 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0010_auto_20180703_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('hp', models.CharField(default='', max_length=20)),
                ('defense', models.CharField(default='', max_length=20)),
                ('atk', models.CharField(default='', max_length=20)),
                ('jpnTitle', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='dungeontoday',
            name='listingDate',
            field=models.DateField(default=datetime.date(2018, 7, 4)),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='monsters',
            field=models.ManyToManyField(to='dungeon.Monster'),
        ),
    ]
