# Generated by Django 2.0.7 on 2018-07-07 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0013_auto_20180705_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='altTitle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='monster',
            name='altTitle2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dungeontoday',
            name='listingDate',
            field=models.DateField(default=datetime.date(2018, 7, 6)),
        ),
    ]
