# Generated by Django 2.0.7 on 2018-07-12 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0016_auto_20180711_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeontoday',
            name='listingDate',
            field=models.DateField(default=datetime.date(2018, 7, 12)),
        ),
    ]
