# Generated by Django 2.0.7 on 2018-12-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaleaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='scoreUp',
            field=models.BooleanField(default=False),
        ),
    ]
