# Generated by Django 2.0.7 on 2018-12-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaleaderboard', '0002_reddituser_scoreup'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='scoreDiff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='scoreDown',
            field=models.BooleanField(default=False),
        ),
    ]
