# Generated by Django 2.0.7 on 2018-12-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaleaderboard', '0003_auto_20181209_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('link', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TopPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('link', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
