# Generated by Django 2.0.7 on 2018-07-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guerrilladungeon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guerrilladungeon',
            name='endTime',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='guerrilladungeon',
            name='startTime',
            field=models.CharField(default='', max_length=200),
        ),
    ]
