# Generated by Django 2.0.7 on 2019-06-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('skill_id', models.IntegerField(default=-1)),
                ('skill_type', models.CharField(default='', max_length=50)),
                ('hp_mult', models.FloatField(default=1)),
                ('atk_mult', models.FloatField(default=1)),
                ('rcv_mult', models.FloatField(default=1)),
                ('dmg_reduction', models.FloatField(default=0)),
                ('skill_part_1_id', models.IntegerField(default=-1)),
                ('skill_part_2_id', models.IntegerField(default=-1)),
                ('skill_part_3_id', models.IntegerField(default=-1)),
                ('skill_class', models.CharField(default='', max_length=100)),
                ('levels', models.IntegerField(default=0)),
                ('max_turns', models.IntegerField(blank=True, default=0)),
                ('min_turns', models.IntegerField(blank=True, default=0)),
                ('server', models.CharField(default='', max_length=2)),
            ],
        ),
    ]
