# Generated by Django 2.0.7 on 2019-06-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='dmg_reduction',
            new_name='shield',
        ),
    ]
