# Generated by Django 2.0.7 on 2019-06-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_auto_20190623_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='atk_mult_full',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='hp_mult_full',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rcv_mult_full',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='shield_full',
            field=models.FloatField(default=1),
        ),
    ]
